#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰍹 󰍹 󰍹 󰍹 󰍹 󰍹 󰍹 󰍹  

bspc config border_width         2
bspc config window_gap          6

bspc config border_radius	12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

xsetroot -cursor_name left_ptr &

nitrogen --restore &
polybar main &
picom &
