#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰍹 󰍹 󰍹 󰍹 󰍹 󰍹 󰍹 󰍹  

bspc config border_width         2
bspc config window_gap          8

bspc config border_radius	6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

nitrogen --restore &
polybar left &
polybar center &
picom &
